version: '3.9'

services:

  discriminators_service_api:
    container_name: Portada_discriminators_service_api
    volumes:
      - '$LOCAL_ADDRESS_AI_MODELS:/models/discriminators_models'
    build:
      context: ../
      dockerfile: .containers/Containerfile.discriminators_service_api
    ports:
      - ${DISCRIMINATORS_API_PORT}:${DISCRIMINATORS_API_PORT}
    networks:
      - portada_net
    environment:
      - DISCRIMINATORS_API_PORT=${DISCRIMINATORS_API_PORT}
      - LOCAL_ADDRESS_AI_MODELS=/models/discriminators_models

  discriminators_service_api_local:
    container_name: Portada_discriminators_service_api
    volumes:
      - '$LOCAL_ADDRESS_AI_MODELS:/models/discriminators_models'
    build:
      context: ../
      dockerfile: .containers/Containerfile.discriminators_service_api_local
    ports:
      - ${DISCRIMINATORS_API_PORT}:${DISCRIMINATORS_API_PORT}
    networks:
      - portada_net
    environment:
      - DISCRIMINATORS_API_PORT=${DISCRIMINATORS_API_PORT}
      - LOCAL_ADDRESS_AI_MODELS=/models/discriminators_models

networks:
  portada_net:
    driver: bridge

volumes:
  dgraph:
