########################################################################################################################
### BASE
########################################################################################################################
FROM python:3.11-slim-buster as base

WORKDIR /app

COPY ./projects/discriminators_service_api/src/ ./projects/discriminators_service_api/requirements.txt ./.containers/discriminator.service.api.sh /app/

########################################################################################################################
### BUILD
########################################################################################################################
FROM base as build

RUN pip install --upgrade pip && \
    pip install --requirement requirements.txt

########################################################################################################################
### APPLICATION ### PROD BUILD: docker build . --tag '<image-ref>:<image-tag>' --target application
########################################################################################################################
FROM build as application

CMD ["bash", "discriminator.service.api.sh"]
